on:
  pull_request:
    types:
      - closed
  issues:
    types:
      - closed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: JasonEtco/smee-action@v2
      with:
        channel: mondeja
