name: Pull Request Labeler
on:
  pull_request_target:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    if: (! contains(github.event.pull_request.labels.*.name, 'release'))
    steps:
    - uses: ericcornelissen/labeler@label-based-on-status
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
